[global]
# Clear all data (but not events)
db_clear = true
# Insert some mock data
db_insert_mock_data = true
# Set timespan for reviews
review_time_days = 0
review_time_hours = 0
review_time_minutes = 4
# Rocket internal db config
# Please specify a correct db string!
[global.databases]
iprp_db = { url = "mysql://root@127.0.0.1:3306/iprp" }